// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class LibreOfficeKitApiPigeonCodecReader: FlutterStandardReader {
}

private class LibreOfficeKitApiPigeonCodecWriter: FlutterStandardWriter {
}

private class LibreOfficeKitApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LibreOfficeKitApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LibreOfficeKitApiPigeonCodecWriter(data: data)
  }
}

class LibreOfficeKitApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LibreOfficeKitApiPigeonCodec(readerWriter: LibreOfficeKitApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LibreOfficeKitApi {
  /// Initializing LibreOffice
  func initialize(completion: @escaping (Result<Void, Error>) -> Void)
  /// Convert any file to another format (PDF by default)
  func convert(filePath: String, outputFormat: String, outputFilePath: String?, outputFileName: String?, filterOptions: String?, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LibreOfficeKitApiSetup {
  static var codec: FlutterStandardMessageCodec { LibreOfficeKitApiPigeonCodec.shared }
  /// Sets up an instance of `LibreOfficeKitApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LibreOfficeKitApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initializing LibreOffice
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libre_office_kit_converter_plugin.LibreOfficeKitApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        api.initialize { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Convert any file to another format (PDF by default)
    let convertChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libre_office_kit_converter_plugin.LibreOfficeKitApi.convert\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      convertChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let outputFormatArg = args[1] as! String
        let outputFilePathArg: String? = nilOrValue(args[2])
        let outputFileNameArg: String? = nilOrValue(args[3])
        let filterOptionsArg: String? = nilOrValue(args[4])
        api.convert(filePath: filePathArg, outputFormat: outputFormatArg, outputFilePath: outputFilePathArg, outputFileName: outputFileNameArg, filterOptions: filterOptionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      convertChannel.setMessageHandler(nil)
    }
  }
}
